-- 0004 — Dossier patient

CREATE TABLE patients (
    id                      BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                    CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    file_number             VARCHAR(30) NULL COMMENT 'N° de dossier attribué par le serveur à la validation',
    user_id                 BIGINT UNSIGNED NULL COMMENT 'Compte patient (application / portail), facultatif',
    first_name              VARCHAR(100) NOT NULL,
    last_name               VARCHAR(100) NOT NULL,
    sex                     CHAR(1) NOT NULL,
    birth_date              DATE NULL,
    birth_date_is_estimated TINYINT(1) NOT NULL DEFAULT 0,
    phone                   VARCHAR(20) NULL COMMENT 'Peut être partagé (ex. enfant sur le téléphone d''un parent)',
    status                  VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    source                  VARCHAR(20) NOT NULL,
    attending_physician_id  BIGINT UNSIGNED NULL COMMENT 'Médecin traitant (D-005)',
    possible_duplicate_of   BIGINT UNSIGNED NULL,
    merged_into_id          BIGINT UNSIGNED NULL,
    validated_by            BIGINT UNSIGNED NULL,
    validated_at            DATETIME NULL,
    rejection_reason        VARCHAR(500) NULL,
    version                 INT UNSIGNED NOT NULL DEFAULT 1,
    created_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by              BIGINT UNSIGNED NULL,
    updated_by              BIGINT UNSIGNED NULL,
    deleted_at              DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_patients_uuid (uuid),
    UNIQUE KEY uq_patients_file_number (file_number),
    UNIQUE KEY uq_patients_user (user_id),
    KEY ix_patients_name (last_name, first_name),
    KEY ix_patients_phone (phone),
    KEY ix_patients_birth_date (birth_date),
    KEY ix_patients_status (status, created_at),
    KEY ix_patients_attending (attending_physician_id),
    CONSTRAINT fk_patients_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_patients_attending FOREIGN KEY (attending_physician_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_patients_duplicate FOREIGN KEY (possible_duplicate_of) REFERENCES patients (id) ON DELETE SET NULL,
    CONSTRAINT fk_patients_merged FOREIGN KEY (merged_into_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_patients_validated_by FOREIGN KEY (validated_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_patients_sex CHECK (sex IN ('M','F')),
    CONSTRAINT ck_patients_status CHECK (status IN ('PENDING','ACTIVE','INACTIVE','REJECTED','MERGED')),
    CONSTRAINT ck_patients_source CHECK (source IN ('APP','WEB','CLINIC','HOMECARE')),
    CONSTRAINT ck_patients_merged CHECK (status <> 'MERGED' OR merged_into_id IS NOT NULL),
    CONSTRAINT ck_patients_active_number CHECK (status <> 'ACTIVE' OR file_number IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE patient_medical_profiles (
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid         CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id   BIGINT UNSIGNED NOT NULL,
    blood_group  VARCHAR(3) NULL,
    observations TEXT NULL,
    version      INT UNSIGNED NOT NULL DEFAULT 1,
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by   BIGINT UNSIGNED NULL,
    updated_by   BIGINT UNSIGNED NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_patient_medical_profiles_uuid (uuid),
    UNIQUE KEY uq_patient_medical_profiles_patient (patient_id),
    CONSTRAINT fk_patient_medical_profiles_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT ck_patient_medical_profiles_blood CHECK (blood_group IS NULL OR blood_group IN ('A+','A-','B+','B-','AB+','AB-','O+','O-'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE patient_contacts (
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid         CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id   BIGINT UNSIGNED NOT NULL,
    full_name    VARCHAR(190) NOT NULL,
    relationship VARCHAR(50)  NULL,
    phone        VARCHAR(20)  NOT NULL,
    is_emergency TINYINT(1) NOT NULL DEFAULT 1,
    version      INT UNSIGNED NOT NULL DEFAULT 1,
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by   BIGINT UNSIGNED NULL,
    updated_by   BIGINT UNSIGNED NULL,
    deleted_at   DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_patient_contacts_uuid (uuid),
    KEY ix_patient_contacts_patient (patient_id),
    CONSTRAINT fk_patient_contacts_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE patient_addresses (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid            CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id      BIGINT UNSIGNED NOT NULL,
    label           VARCHAR(50)  NULL COMMENT 'Domicile, travail…',
    city            VARCHAR(100) NULL,
    district        VARCHAR(100) NULL COMMENT 'Quartier',
    address_line    VARCHAR(255) NULL,
    landmark        VARCHAR(255) NULL COMMENT 'Point de repère (adresses souvent informelles)',
    latitude        DECIMAL(10,7) NULL,
    longitude       DECIMAL(10,7) NULL,
    gps_accuracy_m  DECIMAL(8,2) NULL,
    gps_captured_at DATETIME NULL,
    is_primary      TINYINT(1) NOT NULL DEFAULT 0,
    version         INT UNSIGNED NOT NULL DEFAULT 1,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by      BIGINT UNSIGNED NULL,
    updated_by      BIGINT UNSIGNED NULL,
    deleted_at      DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_patient_addresses_uuid (uuid),
    KEY ix_patient_addresses_patient (patient_id),
    CONSTRAINT fk_patient_addresses_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT ck_patient_addresses_lat CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_patient_addresses_lng CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_patient_addresses_pair CHECK ((latitude IS NULL) = (longitude IS NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE medical_history (
    id           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid         CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id   BIGINT UNSIGNED NOT NULL,
    history_type VARCHAR(20) NOT NULL,
    description  TEXT NOT NULL,
    since_date   DATE NULL,
    recorded_by  BIGINT UNSIGNED NULL,
    version      INT UNSIGNED NOT NULL DEFAULT 1,
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by   BIGINT UNSIGNED NULL,
    updated_by   BIGINT UNSIGNED NULL,
    deleted_at   DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_medical_history_uuid (uuid),
    KEY ix_medical_history_patient (patient_id),
    CONSTRAINT fk_medical_history_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_medical_history_recorded_by FOREIGN KEY (recorded_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_medical_history_type CHECK (history_type IN ('MEDICAL','SURGICAL','FAMILY','OBSTETRIC','OTHER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE allergies (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid        CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id  BIGINT UNSIGNED NOT NULL,
    allergen    VARCHAR(190) NOT NULL,
    medication_id BIGINT UNSIGNED NULL COMMENT 'Si l''allergène est un médicament du référentiel (alertes à la prescription)',
    reaction    VARCHAR(255) NULL,
    severity    VARCHAR(10) NOT NULL DEFAULT 'INCONNUE',
    recorded_by BIGINT UNSIGNED NULL,
    version     INT UNSIGNED NOT NULL DEFAULT 1,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by  BIGINT UNSIGNED NULL,
    updated_by  BIGINT UNSIGNED NULL,
    deleted_at  DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_allergies_uuid (uuid),
    KEY ix_allergies_patient (patient_id),
    CONSTRAINT fk_allergies_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_allergies_medication FOREIGN KEY (medication_id) REFERENCES medications (id) ON DELETE RESTRICT,
    CONSTRAINT fk_allergies_recorded_by FOREIGN KEY (recorded_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_allergies_severity CHECK (severity IN ('LEGERE','MODEREE','SEVERE','INCONNUE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE patient_current_treatments (
    id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid          CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id    BIGINT UNSIGNED NOT NULL,
    medication_id BIGINT UNSIGNED NULL,
    label         VARCHAR(190) NOT NULL,
    dosage        VARCHAR(190) NULL,
    started_on    DATE NULL,
    ended_on      DATE NULL,
    recorded_by   BIGINT UNSIGNED NULL,
    version       INT UNSIGNED NOT NULL DEFAULT 1,
    created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by    BIGINT UNSIGNED NULL,
    updated_by    BIGINT UNSIGNED NULL,
    deleted_at    DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_patient_current_treatments_uuid (uuid),
    KEY ix_patient_current_treatments_patient (patient_id),
    CONSTRAINT fk_patient_current_treatments_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_patient_current_treatments_medication FOREIGN KEY (medication_id) REFERENCES medications (id) ON DELETE RESTRICT,
    CONSTRAINT fk_patient_current_treatments_recorded_by FOREIGN KEY (recorded_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_patient_current_treatments_period CHECK (ended_on IS NULL OR started_on IS NULL OR ended_on >= started_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
