-- 0005 — Rendez-vous

CREATE TABLE appointments (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid            CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id      BIGINT UNSIGNED NOT NULL,
    service_id      BIGINT UNSIGNED NOT NULL,
    practitioner_id BIGINT UNSIGNED NULL,
    scheduled_start DATETIME NOT NULL,
    scheduled_end   DATETIME NOT NULL,
    reason          VARCHAR(500) NULL,
    status          VARCHAR(10) NOT NULL DEFAULT 'DEMANDE',
    requested_by    BIGINT UNSIGNED NOT NULL,
    confirmed_by    BIGINT UNSIGNED NULL,
    confirmed_at    DATETIME NULL,
    rescheduled_from DATETIME NULL COMMENT 'Début initial en cas de déplacement',
    cancelled_by    BIGINT UNSIGNED NULL,
    cancelled_at    DATETIME NULL,
    cancel_reason   VARCHAR(500) NULL,
    checked_in_at   DATETIME NULL,
    version         INT UNSIGNED NOT NULL DEFAULT 1,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by      BIGINT UNSIGNED NULL,
    updated_by      BIGINT UNSIGNED NULL,
    deleted_at      DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_appointments_uuid (uuid),
    KEY ix_appointments_service_start (service_id, scheduled_start),
    KEY ix_appointments_practitioner_start (practitioner_id, scheduled_start),
    KEY ix_appointments_patient_start (patient_id, scheduled_start),
    KEY ix_appointments_status_start (status, scheduled_start),
    CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_service FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_practitioner FOREIGN KEY (practitioner_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_requested_by FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_appointments_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_appointments_status CHECK (status IN ('DEMANDE','CONFIRME','DEPLACE','ANNULE','HONORE','ABSENT')),
    CONSTRAINT ck_appointments_period CHECK (scheduled_end > scheduled_start),
    CONSTRAINT ck_appointments_cancel CHECK (status <> 'ANNULE' OR cancelled_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
