-- 0006 — Consultations et soins à domicile (machine à états : voir docs, D-003)

CREATE TABLE homecare_requests (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid             CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id       BIGINT UNSIGNED NOT NULL,
    requested_by     BIGINT UNSIGNED NOT NULL,
    reason           TEXT NOT NULL,
    urgency          VARCHAR(10) NOT NULL DEFAULT 'NORMALE',
    preferred_time   DATETIME NULL,
    latitude         DECIMAL(10,7) NULL,
    longitude        DECIMAL(10,7) NULL,
    gps_accuracy_m   DECIMAL(8,2) NULL,
    gps_captured_at  DATETIME NULL,
    address_text     VARCHAR(255) NULL,
    landmark         VARCHAR(255) NULL,
    contact_phone    VARCHAR(20) NOT NULL,
    status           VARCHAR(20) NOT NULL DEFAULT 'NOUVELLE',
    assigned_team_id BIGINT UNSIGNED NULL,
    assigned_by      BIGINT UNSIGNED NULL,
    assigned_at      DATETIME NULL,
    cancel_reason    VARCHAR(500) NULL,
    failure_reason   VARCHAR(500) NULL,
    closed_at        DATETIME NULL,
    version          INT UNSIGNED NOT NULL DEFAULT 1,
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by       BIGINT UNSIGNED NULL,
    updated_by       BIGINT UNSIGNED NULL,
    deleted_at       DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_homecare_requests_uuid (uuid),
    KEY ix_homecare_requests_status (status, created_at),
    KEY ix_homecare_requests_team_status (assigned_team_id, status),
    KEY ix_homecare_requests_patient (patient_id, created_at),
    CONSTRAINT fk_homecare_requests_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homecare_requests_requested_by FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homecare_requests_team FOREIGN KEY (assigned_team_id) REFERENCES teams (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homecare_requests_assigned_by FOREIGN KEY (assigned_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_homecare_requests_urgency CHECK (urgency IN ('NORMALE','URGENTE')),
    CONSTRAINT ck_homecare_requests_status CHECK (status IN (
        'NOUVELLE','EN_ATTENTE','PRISE_EN_CHARGE','EN_ROUTE','SUR_PLACE','EN_COURS','TERMINEE','FACTUREE',
        'ANNULEE_PATIENT','ANNULEE_CLINIQUE','ECHEC')),
    CONSTRAINT ck_homecare_requests_lat CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_homecare_requests_lng CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    CONSTRAINT ck_homecare_requests_pair CHECK ((latitude IS NULL) = (longitude IS NULL)),
    CONSTRAINT ck_homecare_requests_team CHECK (
        status IN ('NOUVELLE','EN_ATTENTE','ANNULEE_PATIENT','ANNULEE_CLINIQUE','ECHEC') OR assigned_team_id IS NOT NULL),
    CONSTRAINT ck_homecare_requests_failure CHECK (status <> 'ECHEC' OR failure_reason IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Historique immuable de chaque transition (qui, quand, où).
CREATE TABLE homecare_status_history (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid        CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_id  BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(20) NULL,
    to_status   VARCHAR(20) NOT NULL,
    changed_by  BIGINT UNSIGNED NOT NULL,
    changed_at  DATETIME NOT NULL COMMENT 'Heure de l''action (côté appareil si hors ligne)',
    received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Heure de réception serveur',
    latitude    DECIMAL(10,7) NULL,
    longitude   DECIMAL(10,7) NULL,
    comment     VARCHAR(500) NULL,
    device_id   BIGINT UNSIGNED NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_homecare_status_history_uuid (uuid),
    KEY ix_homecare_status_history_request (request_id, changed_at),
    CONSTRAINT fk_homecare_status_history_request FOREIGN KEY (request_id) REFERENCES homecare_requests (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homecare_status_history_user FOREIGN KEY (changed_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homecare_status_history_device FOREIGN KEY (device_id) REFERENCES devices (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Une demande peut connaître plusieurs prises en charge successives (désistement d'une équipe) ;
-- une seule est active à la fois (released_at IS NULL), garanti par le service.
CREATE TABLE homecare_interventions (
    id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid           CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    request_id     BIGINT UNSIGNED NOT NULL,
    team_id        BIGINT UNSIGNED NOT NULL,
    accepted_by    BIGINT UNSIGNED NOT NULL,
    accepted_at    DATETIME NOT NULL,
    departed_at    DATETIME NULL,
    arrived_at     DATETIME NULL,
    started_at     DATETIME NULL,
    completed_at   DATETIME NULL,
    released_at    DATETIME NULL,
    release_reason VARCHAR(500) NULL,
    version        INT UNSIGNED NOT NULL DEFAULT 1,
    created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by     BIGINT UNSIGNED NULL,
    updated_by     BIGINT UNSIGNED NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_homecare_interventions_uuid (uuid),
    KEY ix_homecare_interventions_request (request_id, released_at),
    KEY ix_homecare_interventions_team (team_id, accepted_at),
    CONSTRAINT fk_homecare_interventions_request FOREIGN KEY (request_id) REFERENCES homecare_requests (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homecare_interventions_team FOREIGN KEY (team_id) REFERENCES teams (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homecare_interventions_accepted_by FOREIGN KEY (accepted_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_homecare_interventions_release CHECK (released_at IS NULL OR release_reason IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE homecare_locations (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid            CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    intervention_id BIGINT UNSIGNED NOT NULL,
    kind            VARCHAR(10) NOT NULL,
    latitude        DECIMAL(10,7) NOT NULL,
    longitude       DECIMAL(10,7) NOT NULL,
    accuracy_m      DECIMAL(8,2) NULL,
    captured_at     DATETIME NOT NULL,
    recorded_by     BIGINT UNSIGNED NOT NULL,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_homecare_locations_uuid (uuid),
    KEY ix_homecare_locations_intervention (intervention_id, captured_at),
    CONSTRAINT fk_homecare_locations_intervention FOREIGN KEY (intervention_id) REFERENCES homecare_interventions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_homecare_locations_user FOREIGN KEY (recorded_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_homecare_locations_kind CHECK (kind IN ('DEPART','ARRIVEE','TRACE')),
    CONSTRAINT ck_homecare_locations_lat CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT ck_homecare_locations_lng CHECK (longitude BETWEEN -180 AND 180)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
