-- 0007 — Consultations, constantes, diagnostics, notes

CREATE TABLE consultations (
    id                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                   CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id             BIGINT UNSIGNED NOT NULL,
    consultation_type      VARCHAR(10) NOT NULL,
    parent_consultation_id BIGINT UNSIGNED NULL COMMENT 'Consultation d''origine pour un suivi',
    appointment_id         BIGINT UNSIGNED NULL,
    homecare_request_id    BIGINT UNSIGNED NULL,
    service_id             BIGINT UNSIGNED NULL,
    practitioner_id        BIGINT UNSIGNED NULL,
    status                 VARCHAR(10) NOT NULL DEFAULT 'OUVERTE',
    chief_complaint        TEXT NULL COMMENT 'Motif',
    symptoms               TEXT NULL,
    clinical_exam          TEXT NULL,
    conclusion             TEXT NULL,
    started_at             DATETIME NOT NULL,
    closed_at              DATETIME NULL,
    closed_by              BIGINT UNSIGNED NULL,
    cancel_reason          VARCHAR(500) NULL,
    version                INT UNSIGNED NOT NULL DEFAULT 1,
    created_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by             BIGINT UNSIGNED NULL,
    updated_by             BIGINT UNSIGNED NULL,
    deleted_at             DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_consultations_uuid (uuid),
    KEY ix_consultations_patient (patient_id, started_at),
    KEY ix_consultations_practitioner (practitioner_id, started_at),
    KEY ix_consultations_status (status, started_at),
    KEY ix_consultations_type (consultation_type, started_at),
    KEY ix_consultations_homecare (homecare_request_id),
    KEY ix_consultations_appointment (appointment_id),
    CONSTRAINT fk_consultations_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultations_parent FOREIGN KEY (parent_consultation_id) REFERENCES consultations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultations_appointment FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultations_homecare FOREIGN KEY (homecare_request_id) REFERENCES homecare_requests (id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultations_service FOREIGN KEY (service_id) REFERENCES services (id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultations_practitioner FOREIGN KEY (practitioner_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultations_closed_by FOREIGN KEY (closed_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_consultations_type CHECK (consultation_type IN ('CLINIQUE','DOMICILE','SUIVI','URGENCE')),
    CONSTRAINT ck_consultations_status CHECK (status IN ('OUVERTE','EN_COURS','CLOTUREE','ANNULEE')),
    CONSTRAINT ck_consultations_domicile CHECK (consultation_type <> 'DOMICILE' OR homecare_request_id IS NOT NULL),
    CONSTRAINT ck_consultations_closed CHECK (status <> 'CLOTUREE' OR closed_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Constantes : une ligne par prise de mesure (ajout seulement), avec ou sans consultation.
-- Seules les impossibilités physiques sont contrôlées ; aucune norme clinique n'est codée ici.
CREATE TABLE vital_signs (
    id                   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                 CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id           BIGINT UNSIGNED NOT NULL,
    consultation_id      BIGINT UNSIGNED NULL,
    temperature_c        DECIMAL(4,1) NULL,
    systolic_mmhg        SMALLINT UNSIGNED NULL,
    diastolic_mmhg       SMALLINT UNSIGNED NULL,
    pulse_bpm            SMALLINT UNSIGNED NULL,
    respiratory_rate     SMALLINT UNSIGNED NULL,
    spo2_percent         TINYINT UNSIGNED NULL,
    weight_kg            DECIMAL(5,2) NULL,
    height_cm            DECIMAL(5,1) NULL,
    glycemia_g_l         DECIMAL(5,2) NULL,
    notes                VARCHAR(500) NULL,
    recorded_by          BIGINT UNSIGNED NOT NULL,
    recorded_at          DATETIME NOT NULL,
    version              INT UNSIGNED NOT NULL DEFAULT 1,
    created_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by           BIGINT UNSIGNED NULL,
    updated_by           BIGINT UNSIGNED NULL,
    deleted_at           DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_vital_signs_uuid (uuid),
    KEY ix_vital_signs_patient (patient_id, recorded_at),
    KEY ix_vital_signs_consultation (consultation_id),
    CONSTRAINT fk_vital_signs_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_vital_signs_consultation FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_vital_signs_recorded_by FOREIGN KEY (recorded_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_vital_signs_spo2 CHECK (spo2_percent IS NULL OR spo2_percent <= 100),
    CONSTRAINT ck_vital_signs_positive CHECK (
        (weight_kg IS NULL OR weight_kg > 0) AND (height_cm IS NULL OR height_cm > 0) AND (glycemia_g_l IS NULL OR glycemia_g_l >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE consultation_diagnoses (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid            CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    consultation_id BIGINT UNSIGNED NOT NULL,
    icd10_code      VARCHAR(10)  NULL COMMENT 'Code CIM-10 facultatif',
    label           VARCHAR(255) NOT NULL,
    diagnosis_kind  VARCHAR(12) NOT NULL DEFAULT 'PRINCIPAL',
    certainty       VARCHAR(10) NOT NULL DEFAULT 'CONFIRME',
    recorded_by     BIGINT UNSIGNED NOT NULL,
    version         INT UNSIGNED NOT NULL DEFAULT 1,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by      BIGINT UNSIGNED NULL,
    updated_by      BIGINT UNSIGNED NULL,
    deleted_at      DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_consultation_diagnoses_uuid (uuid),
    KEY ix_consultation_diagnoses_consultation (consultation_id),
    KEY ix_consultation_diagnoses_icd10 (icd10_code),
    CONSTRAINT fk_consultation_diagnoses_consultation FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultation_diagnoses_recorded_by FOREIGN KEY (recorded_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_consultation_diagnoses_kind CHECK (diagnosis_kind IN ('PRINCIPAL','SECONDAIRE')),
    CONSTRAINT ck_consultation_diagnoses_certainty CHECK (certainty IN ('CONFIRME','PROBABLE','SUSPECTE'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Après clôture, la consultation n'est plus modifiée : les corrections sont des notes de type ADDENDUM.
CREATE TABLE consultation_notes (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid            CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    consultation_id BIGINT UNSIGNED NOT NULL,
    author_id       BIGINT UNSIGNED NOT NULL,
    note_kind       VARCHAR(10) NOT NULL DEFAULT 'NOTE',
    content         TEXT NOT NULL,
    version         INT UNSIGNED NOT NULL DEFAULT 1,
    created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by      BIGINT UNSIGNED NULL,
    updated_by      BIGINT UNSIGNED NULL,
    deleted_at      DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_consultation_notes_uuid (uuid),
    KEY ix_consultation_notes_consultation (consultation_id, created_at),
    CONSTRAINT fk_consultation_notes_consultation FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_consultation_notes_author FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_consultation_notes_kind CHECK (note_kind IN ('NOTE','ADDENDUM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
