-- 0008 — Soins

CREATE TABLE treatments (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id          BIGINT UNSIGNED NOT NULL,
    consultation_id     BIGINT UNSIGNED NULL,
    homecare_request_id BIGINT UNSIGNED NULL,
    treatment_type_id   BIGINT UNSIGNED NOT NULL,
    status              VARCHAR(10) NOT NULL DEFAULT 'REALISE',
    scheduled_for       DATETIME NULL COMMENT 'Soin programmé (ex. pansement quotidien)',
    performed_by        BIGINT UNSIGNED NULL,
    performed_at        DATETIME NULL,
    observations        TEXT NULL,
    cancel_reason       VARCHAR(500) NULL,
    version             INT UNSIGNED NOT NULL DEFAULT 1,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by          BIGINT UNSIGNED NULL,
    updated_by          BIGINT UNSIGNED NULL,
    deleted_at          DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_treatments_uuid (uuid),
    KEY ix_treatments_patient (patient_id, performed_at),
    KEY ix_treatments_performer (performed_by, performed_at),
    KEY ix_treatments_consultation (consultation_id),
    KEY ix_treatments_homecare (homecare_request_id),
    KEY ix_treatments_status (status, scheduled_for),
    CONSTRAINT fk_treatments_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_treatments_consultation FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_treatments_homecare FOREIGN KEY (homecare_request_id) REFERENCES homecare_requests (id) ON DELETE RESTRICT,
    CONSTRAINT fk_treatments_type FOREIGN KEY (treatment_type_id) REFERENCES treatment_types (id) ON DELETE RESTRICT,
    CONSTRAINT fk_treatments_performer FOREIGN KEY (performed_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_treatments_status CHECK (status IN ('PLANIFIE','REALISE','ANNULE')),
    CONSTRAINT ck_treatments_done CHECK (status <> 'REALISE' OR (performed_by IS NOT NULL AND performed_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
