-- 0009 — Examens, résultats, pièces jointes

CREATE TABLE examinations (
    id                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id          BIGINT UNSIGNED NOT NULL,
    consultation_id     BIGINT UNSIGNED NULL,
    examination_type_id BIGINT UNSIGNED NOT NULL,
    priority            VARCHAR(10) NOT NULL DEFAULT 'NORMALE',
    clinical_info       TEXT NULL COMMENT 'Renseignements cliniques utiles au technicien',
    prescribed_by       BIGINT UNSIGNED NOT NULL,
    prescribed_at       DATETIME NOT NULL,
    technician_id       BIGINT UNSIGNED NULL,
    performed_at        DATETIME NULL,
    completed_at        DATETIME NULL,
    status              VARCHAR(10) NOT NULL DEFAULT 'PRESCRIT',
    validated_by        BIGINT UNSIGNED NULL,
    validated_at        DATETIME NULL,
    comment             TEXT NULL,
    cancel_reason       VARCHAR(500) NULL,
    version             INT UNSIGNED NOT NULL DEFAULT 1,
    created_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by          BIGINT UNSIGNED NULL,
    updated_by          BIGINT UNSIGNED NULL,
    deleted_at          DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_examinations_uuid (uuid),
    KEY ix_examinations_status (status, prescribed_at),
    KEY ix_examinations_patient (patient_id, prescribed_at),
    KEY ix_examinations_technician (technician_id, status),
    KEY ix_examinations_prescriber (prescribed_by, prescribed_at),
    KEY ix_examinations_consultation (consultation_id),
    CONSTRAINT fk_examinations_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_examinations_consultation FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_examinations_type FOREIGN KEY (examination_type_id) REFERENCES examination_types (id) ON DELETE RESTRICT,
    CONSTRAINT fk_examinations_prescriber FOREIGN KEY (prescribed_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_examinations_technician FOREIGN KEY (technician_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_examinations_validator FOREIGN KEY (validated_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_examinations_priority CHECK (priority IN ('NORMALE','URGENTE')),
    CONSTRAINT ck_examinations_status CHECK (status IN ('PRESCRIT','EN_ATTENTE','EN_COURS','TERMINE','VALIDE','ANNULE')),
    CONSTRAINT ck_examinations_validated CHECK (status <> 'VALIDE' OR (validated_by IS NOT NULL AND validated_at IS NOT NULL)),
    -- D-005 : séparation des tâches, le technicien ne valide pas ses propres résultats.
    CONSTRAINT ck_examinations_segregation CHECK (validated_by IS NULL OR technician_id IS NULL OR validated_by <> technician_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE examination_results (
    id             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid           CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    examination_id BIGINT UNSIGNED NOT NULL,
    parameter_id   BIGINT UNSIGNED NULL COMMENT 'NULL = résultat libre',
    label          VARCHAR(190) NOT NULL,
    value_numeric  DECIMAL(14,4) NULL,
    value_text     TEXT NULL,
    unit           VARCHAR(30) NULL,
    reference_text VARCHAR(190) NULL COMMENT 'Valeurs de référence copiées au moment de la saisie',
    is_abnormal    TINYINT(1) NULL,
    recorded_by    BIGINT UNSIGNED NOT NULL,
    recorded_at    DATETIME NOT NULL,
    version        INT UNSIGNED NOT NULL DEFAULT 1,
    created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by     BIGINT UNSIGNED NULL,
    updated_by     BIGINT UNSIGNED NULL,
    deleted_at     DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_examination_results_uuid (uuid),
    KEY ix_examination_results_examination (examination_id),
    CONSTRAINT fk_examination_results_examination FOREIGN KEY (examination_id) REFERENCES examinations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_examination_results_parameter FOREIGN KEY (parameter_id) REFERENCES examination_type_parameters (id) ON DELETE RESTRICT,
    CONSTRAINT fk_examination_results_recorded_by FOREIGN KEY (recorded_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_examination_results_value CHECK (value_numeric IS NOT NULL OR value_text IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Fichiers stockés hors du dossier public (storage/uploads), sous un nom aléatoire.
-- owner_id référence la table indiquée par owner_type (contrôle applicatif) ; patient_id sert au contrôle d'accès.
CREATE TABLE attachments (
    id            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid          CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    owner_type    VARCHAR(20) NOT NULL,
    owner_id      BIGINT UNSIGNED NOT NULL,
    patient_id    BIGINT UNSIGNED NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_path   VARCHAR(255) NOT NULL COMMENT 'Chemin relatif à storage/uploads',
    mime_type     VARCHAR(100) NOT NULL,
    size_bytes    INT UNSIGNED NOT NULL,
    sha256        CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    uploaded_by   BIGINT UNSIGNED NOT NULL,
    version       INT UNSIGNED NOT NULL DEFAULT 1,
    created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at    DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_attachments_uuid (uuid),
    UNIQUE KEY uq_attachments_stored_path (stored_path),
    KEY ix_attachments_owner (owner_type, owner_id),
    KEY ix_attachments_patient (patient_id),
    CONSTRAINT fk_attachments_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_attachments_uploaded_by FOREIGN KEY (uploaded_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_attachments_owner CHECK (owner_type IN ('EXAMINATION','CONSULTATION','PATIENT')),
    CONSTRAINT ck_attachments_size CHECK (size_bytes > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
