-- 0010 — Ordonnances et modèles d'ordonnance
-- Les modèles sont des DONNÉES configurées par la clinique (aucune prescription codée en dur).
-- Le prescripteur reste responsable : chaque ligne issue d'un modèle est modifiable avant signature.

CREATE TABLE prescription_templates (
    id                    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                  CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    name                  VARCHAR(190) NOT NULL,
    pathology             VARCHAR(190) NOT NULL,
    population            VARCHAR(12) NOT NULL,
    age_min_months        SMALLINT UNSIGNED NULL,
    age_max_months        SMALLINT UNSIGNED NULL,
    weight_min_kg         DECIMAL(5,2) NULL,
    weight_max_kg         DECIMAL(5,2) NULL,
    contraindications_note TEXT NULL,
    usage_notes           TEXT NULL,
    template_version      INT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Version clinique du protocole (≠ version de sync)',
    status                VARCHAR(10) NOT NULL DEFAULT 'BROUILLON',
    approved_by           BIGINT UNSIGNED NULL,
    approved_at           DATETIME NULL,
    version               INT UNSIGNED NOT NULL DEFAULT 1,
    created_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by            BIGINT UNSIGNED NULL,
    updated_by            BIGINT UNSIGNED NULL,
    deleted_at            DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_prescription_templates_uuid (uuid),
    KEY ix_prescription_templates_lookup (status, pathology),
    CONSTRAINT fk_prescription_templates_approved_by FOREIGN KEY (approved_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_prescription_templates_population CHECK (population IN ('ADULTE','ENFANT','NOURRISSON','AUTRE')),
    CONSTRAINT ck_prescription_templates_status CHECK (status IN ('BROUILLON','ACTIF','ARCHIVE')),
    CONSTRAINT ck_prescription_templates_approved CHECK (status <> 'ACTIF' OR (approved_by IS NOT NULL AND approved_at IS NOT NULL)),
    CONSTRAINT ck_prescription_templates_age CHECK (age_min_months IS NULL OR age_max_months IS NULL OR age_max_months >= age_min_months),
    CONSTRAINT ck_prescription_templates_weight CHECK (weight_min_kg IS NULL OR weight_max_kg IS NULL OR weight_max_kg >= weight_min_kg)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE prescription_template_items (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid             CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    template_id      BIGINT UNSIGNED NOT NULL,
    medication_id    BIGINT UNSIGNED NULL,
    medication_label VARCHAR(190) NOT NULL,
    dosage           VARCHAR(100) NULL,
    form             VARCHAR(60)  NULL,
    quantity         VARCHAR(60)  NULL,
    posology         VARCHAR(255) NULL,
    frequency        VARCHAR(100) NULL,
    duration         VARCHAR(100) NULL,
    route            VARCHAR(60)  NULL,
    instructions     VARCHAR(500) NULL,
    sort_order       SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_prescription_template_items_uuid (uuid),
    KEY ix_prescription_template_items_template (template_id, sort_order),
    CONSTRAINT fk_prescription_template_items_template FOREIGN KEY (template_id) REFERENCES prescription_templates (id) ON DELETE RESTRICT,
    CONSTRAINT fk_prescription_template_items_medication FOREIGN KEY (medication_id) REFERENCES medications (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE prescriptions (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid             CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    patient_id       BIGINT UNSIGNED NOT NULL,
    consultation_id  BIGINT UNSIGNED NULL,
    prescriber_id    BIGINT UNSIGNED NOT NULL,
    template_id      BIGINT UNSIGNED NULL,
    template_version INT UNSIGNED NULL,
    status           VARCHAR(10) NOT NULL DEFAULT 'BROUILLON',
    signed_at        DATETIME NULL,
    notes            TEXT NULL,
    cancel_reason    VARCHAR(500) NULL,
    version          INT UNSIGNED NOT NULL DEFAULT 1,
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by       BIGINT UNSIGNED NULL,
    updated_by       BIGINT UNSIGNED NULL,
    deleted_at       DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_prescriptions_uuid (uuid),
    KEY ix_prescriptions_patient (patient_id, created_at),
    KEY ix_prescriptions_prescriber (prescriber_id, created_at),
    KEY ix_prescriptions_consultation (consultation_id),
    CONSTRAINT fk_prescriptions_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_prescriptions_consultation FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_prescriptions_prescriber FOREIGN KEY (prescriber_id) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_prescriptions_template FOREIGN KEY (template_id) REFERENCES prescription_templates (id) ON DELETE RESTRICT,
    CONSTRAINT ck_prescriptions_status CHECK (status IN ('BROUILLON','SIGNEE','ANNULEE')),
    CONSTRAINT ck_prescriptions_signed CHECK (status <> 'SIGNEE' OR signed_at IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE prescription_items (
    id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid             CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    prescription_id  BIGINT UNSIGNED NOT NULL,
    medication_id    BIGINT UNSIGNED NULL,
    medication_label VARCHAR(190) NOT NULL COMMENT 'Libellé figé au moment de la prescription',
    dosage           VARCHAR(100) NULL,
    form             VARCHAR(60)  NULL,
    quantity         VARCHAR(60)  NULL,
    posology         VARCHAR(255) NULL,
    frequency        VARCHAR(100) NULL,
    duration         VARCHAR(100) NULL,
    route            VARCHAR(60)  NULL,
    instructions     VARCHAR(500) NULL,
    sort_order       SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    version          INT UNSIGNED NOT NULL DEFAULT 1,
    created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by       BIGINT UNSIGNED NULL,
    updated_by       BIGINT UNSIGNED NULL,
    deleted_at       DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_prescription_items_uuid (uuid),
    KEY ix_prescription_items_prescription (prescription_id, sort_order),
    CONSTRAINT fk_prescription_items_prescription FOREIGN KEY (prescription_id) REFERENCES prescriptions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_prescription_items_medication FOREIGN KEY (medication_id) REFERENCES medications (id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
