-- 0011 — Facturation (D-004 : paiements hors plateforme, état de règlement déclaratif)

CREATE TABLE invoices (
    id                     BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid                   CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    number                 VARCHAR(30) NULL COMMENT 'N° définitif attribué par le serveur à l''émission',
    provisional_number     VARCHAR(40) NULL COMMENT 'N° provisoire affiché avant émission (hors ligne)',
    patient_id             BIGINT UNSIGNED NOT NULL,
    consultation_id        BIGINT UNSIGNED NULL,
    homecare_request_id    BIGINT UNSIGNED NULL,
    status                 VARCHAR(10) NOT NULL DEFAULT 'BROUILLON',
    currency               CHAR(3) NOT NULL DEFAULT 'XOF',
    total_amount           BIGINT UNSIGNED NOT NULL DEFAULT 0,
    discount_amount        BIGINT UNSIGNED NOT NULL DEFAULT 0,
    net_amount             BIGINT UNSIGNED NOT NULL DEFAULT 0,
    settlement_status      VARCHAR(20) NOT NULL DEFAULT 'NON_REGLEE',
    declared_paid_amount   BIGINT UNSIGNED NOT NULL DEFAULT 0,
    settlement_declared_at DATETIME NULL,
    settlement_declared_by BIGINT UNSIGNED NULL,
    issued_at              DATETIME NULL,
    issued_by              BIGINT UNSIGNED NULL,
    cancelled_at           DATETIME NULL,
    cancelled_by           BIGINT UNSIGNED NULL,
    cancel_reason          VARCHAR(500) NULL,
    notes                  VARCHAR(500) NULL,
    version                INT UNSIGNED NOT NULL DEFAULT 1,
    created_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by             BIGINT UNSIGNED NULL,
    updated_by             BIGINT UNSIGNED NULL,
    deleted_at             DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_invoices_uuid (uuid),
    UNIQUE KEY uq_invoices_number (number),
    KEY ix_invoices_patient (patient_id, created_at),
    KEY ix_invoices_status (status, issued_at),
    KEY ix_invoices_settlement (settlement_status, issued_at),
    KEY ix_invoices_consultation (consultation_id),
    KEY ix_invoices_homecare (homecare_request_id),
    CONSTRAINT fk_invoices_patient FOREIGN KEY (patient_id) REFERENCES patients (id) ON DELETE RESTRICT,
    CONSTRAINT fk_invoices_consultation FOREIGN KEY (consultation_id) REFERENCES consultations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_invoices_homecare FOREIGN KEY (homecare_request_id) REFERENCES homecare_requests (id) ON DELETE RESTRICT,
    CONSTRAINT fk_invoices_settlement_by FOREIGN KEY (settlement_declared_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_invoices_issued_by FOREIGN KEY (issued_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT fk_invoices_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_invoices_status CHECK (status IN ('BROUILLON','EMISE','ANNULEE')),
    CONSTRAINT ck_invoices_settlement CHECK (settlement_status IN ('NON_REGLEE','PARTIELLEMENT_REGLEE','REGLEE')),
    CONSTRAINT ck_invoices_amounts CHECK (discount_amount <= total_amount AND net_amount = total_amount - discount_amount),
    CONSTRAINT ck_invoices_declared CHECK (declared_paid_amount <= net_amount),
    CONSTRAINT ck_invoices_issued CHECK (status = 'BROUILLON' OR (number IS NOT NULL AND issued_at IS NOT NULL) OR status = 'ANNULEE'),
    CONSTRAINT ck_invoices_cancelled CHECK (status <> 'ANNULEE' OR (cancelled_at IS NOT NULL AND cancel_reason IS NOT NULL)),
    CONSTRAINT ck_invoices_settlement_only_issued CHECK (settlement_status = 'NON_REGLEE' OR status = 'EMISE')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Lignes : libellé et prix COPIÉS au moment de la facturation (le tarif peut évoluer ensuite).
CREATE TABLE invoice_items (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    uuid        CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    invoice_id  BIGINT UNSIGNED NOT NULL,
    item_type   VARCHAR(20) NOT NULL,
    source_uuid CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL COMMENT 'uuid du soin / examen / acte facturé',
    tariff_id   BIGINT UNSIGNED NULL,
    description VARCHAR(255) NOT NULL,
    quantity    INT UNSIGNED NOT NULL DEFAULT 1,
    unit_price  BIGINT UNSIGNED NOT NULL,
    total_price BIGINT UNSIGNED NOT NULL,
    sort_order  SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    version     INT UNSIGNED NOT NULL DEFAULT 1,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by  BIGINT UNSIGNED NULL,
    updated_by  BIGINT UNSIGNED NULL,
    deleted_at  DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_invoice_items_uuid (uuid),
    KEY ix_invoice_items_invoice (invoice_id, sort_order),
    KEY ix_invoice_items_source (source_uuid),
    CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE RESTRICT,
    CONSTRAINT fk_invoice_items_tariff FOREIGN KEY (tariff_id) REFERENCES tariffs (id) ON DELETE RESTRICT,
    CONSTRAINT ck_invoice_items_type CHECK (item_type IN ('MEDICAL_ACT','TREATMENT','EXAMINATION','MEDICATION','OTHER')),
    CONSTRAINT ck_invoice_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_invoice_items_total CHECK (total_price = quantity * unit_price)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE invoice_status_history (
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    invoice_id BIGINT UNSIGNED NOT NULL,
    field_name VARCHAR(10) NOT NULL,
    from_value VARCHAR(20) NULL,
    to_value   VARCHAR(20) NOT NULL,
    amount     BIGINT UNSIGNED NULL COMMENT 'Montant déclaré (changement de règlement)',
    changed_by BIGINT UNSIGNED NOT NULL,
    changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    comment    VARCHAR(500) NULL,
    PRIMARY KEY (id),
    KEY ix_invoice_status_history_invoice (invoice_id, changed_at),
    CONSTRAINT fk_invoice_status_history_invoice FOREIGN KEY (invoice_id) REFERENCES invoices (id) ON DELETE RESTRICT,
    CONSTRAINT fk_invoice_status_history_user FOREIGN KEY (changed_by) REFERENCES users (id) ON DELETE RESTRICT,
    CONSTRAINT ck_invoice_status_history_field CHECK (field_name IN ('STATUS','SETTLEMENT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
